<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-HGE39OB" ignored="0" name="Default test" tests="2" failures="0" timestamp="2019-11-07T23:11:03 IST" time="29.174" errors="0">
  <testcase name="@BeforeMethod ApplicationLogin" time="0.279" classname="com.automationtalks.RegressionSuite.VehicalInsuranceCalculator">
    <failure type="io.github.bonigarcia.wdm.WebDriverManagerException" message="java.net.NoRouteToHostException: No route to host: connect">
      <![CDATA[io.github.bonigarcia.wdm.WebDriverManagerException: java.net.NoRouteToHostException: No route to host: connect
at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:754)
at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:563)
at io.github.bonigarcia.wdm.WebDriverManager.handleException(WebDriverManager.java:751)
at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:563)
at io.github.bonigarcia.wdm.WebDriverManager.setup(WebDriverManager.java:260)
at com.automationtalks.TestBaseLibrary.TestBase.launchBrowser(TestBase.java:24)
at com.automationtalks.RegressionSuite.VehicalInsuranceCalculator.ApplicationLogin(VehicalInsuranceCalculator.java:26)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:340)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:294)
at org.testng.internal.TestInvoker.runConfigMethods(TestInvoker.java:683)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:510)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
Caused by: java.net.NoRouteToHostException: No route to host: connect
at java.net.DualStackPlainSocketImpl.connect0(Native Method)
at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
at java.net.PlainSocketImpl.connect(Unknown Source)
at java.net.SocksSocketImpl.connect(Unknown Source)
at java.net.Socket.connect(Unknown Source)
at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:339)
at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:373)
at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:394)
at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:237)
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
at io.github.bonigarcia.wdm.HttpClient.execute(HttpClient.java:169)
at io.github.bonigarcia.wdm.WebDriverManager.getDriversFromXml(WebDriverManager.java:1045)
at io.github.bonigarcia.wdm.InternetExplorerDriverManager.getDrivers(InternetExplorerDriverManager.java:77)
at io.github.bonigarcia.wdm.WebDriverManager.filterCandidateUrls(WebDriverManager.java:770)
at io.github.bonigarcia.wdm.WebDriverManager.manage(WebDriverManager.java:549)
... 37 more
]]>
    </failure>
  </testcase> <!-- @BeforeMethod ApplicationLogin -->
  <testcase name="@AfterMethod tearDown" time="-1.573148463841E9" classname="com.automationtalks.RegressionSuite.VehicalInsuranceCalculator">
    <skipped/>
  </testcase> <!-- @AfterMethod tearDown -->
  <testcase name="motorCycleInsuranceCalculation" time="0.01" classname="com.automationtalks.RegressionSuite.VehicalInsuranceCalculator"/>
  <testcase name="motorCycleInsuranceCalculation1" time="0.0" classname="com.automationtalks.RegressionSuite.VehicalInsuranceCalculator">
    <skipped/>
  </testcase> <!-- motorCycleInsuranceCalculation1 -->
</testsuite> <!-- Default test -->
